num_clients: 10
num_rounds: 20
max_num_rounds: 20
local_epochs: 2
learning_rate: 0.01
batch_size: 32
aggregation: fedavg
model: cnn
dataset: mnist
dropout_prob: 0.1
min_clients_to_aggregate: 8
max_parallel_clients: 10
reconnect_delay: 0.5
max_retries: 3
max_wait_time: 5.0
secure_aggregation: scsecagg
benchmark:
  enable: true
  csv_path: results/logs/bench.csv
scsecagg:
  num_servers: 6
  read_threshold: 4
  storage_factor: 2
early_stop:
  enable: true
  target_accuracy: 0.95
  patience: 5
  min_delta: 0.001
